name: Github Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'EnReachNetwork/enreach-docs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node v18
        uses: actions/setup-node@v1
        with:
          node-version: v18.18.0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build for production
        run: yarn build
        env:
          SITE_URL: "https://docs.${{ matrix.domain }}"

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: docs.enreach.network
